# dreamzsh/core/config.zsh

if [[ -n "${__DREAMZSH_CONFIG_LOADED:-}" ]]; then
  return 0
fi
__DREAMZSH_CONFIG_LOADED=1

source "${DREAMZSH_DIR}/core/utils.zsh" || return 1

typeset -g DREAMZSH_THEME=""
typeset -ga DREAMZSH_PLUGINS=()
typeset -g DREAMZSH_PROFILE=""
typeset -g DREAMZSH_CONFIG_VERSION="2"

dz::config::set_defaults() {
  : "${DREAMZSH_THEME:=minimal}"
  : "${DREAMZSH_PROFILE:=default}"

  if (( ${#DREAMZSH_PLUGINS[@]} == 0 )); then
    DREAMZSH_PLUGINS=(git history navigation)
  fi
}

dz::config::load() {
  local product_version="$DREAMZSH_VERSION"
  if [[ -f "$DREAMZSH_CONFIG_FILE" ]]; then
    source "$DREAMZSH_CONFIG_FILE" || {
      dz::error "Failed to load config: $DREAMZSH_CONFIG_FILE"
      return 1
    }
    if [[ "$DREAMZSH_VERSION" == <-> ]]; then
      DREAMZSH_CONFIG_VERSION="$DREAMZSH_VERSION"
      DREAMZSH_VERSION="$product_version"
    fi
  fi

  dz::config::set_defaults
}

dz::config::save() {
  local config_file="$DREAMZSH_CONFIG_FILE"
  local config_dir
  local tmp_file

  if [[ -L "$config_file" ]]; then
    config_file="${config_file:A}"
  fi

  config_dir="${config_file:h}"

  dz::ensure_dir "$config_dir" || return 1

  tmp_file="$(mktemp "$config_dir/.dreamzsh.conf.tmp.XXXXXX")" || {
    dz::error "Failed to create temporary config file in: $config_dir"
    return 1
  }

  cat >| "$tmp_file" <<EOF
# DreamZSH configuration
# Generated by DreamZSH CLI

DREAMZSH_CONFIG_VERSION="2"
DREAMZSH_THEME="${DREAMZSH_THEME}"
DREAMZSH_PROFILE="${DREAMZSH_PROFILE}"
DREAMZSH_PLUGINS=(${(j: :)${(q)DREAMZSH_PLUGINS[@]}})
EOF

  if (( $? != 0 )); then
    rm -f -- "$tmp_file"
    dz::error "Failed to write config: $DREAMZSH_CONFIG_FILE"
    return 1
  fi

  mv -f -- "$tmp_file" "$config_file" || {
    rm -f -- "$tmp_file"
    dz::error "Failed to replace config: $DREAMZSH_CONFIG_FILE"
    return 1
  }
}

dz::config::print() {
  print -r -- "DREAMZSH_CONFIG_VERSION=\"$DREAMZSH_CONFIG_VERSION\""
  print -r -- "DREAMZSH_THEME=\"$DREAMZSH_THEME\""
  print -r -- "DREAMZSH_PROFILE=\"$DREAMZSH_PROFILE\""
  print -r -- "DREAMZSH_PLUGINS=(${(j: :)${(q)DREAMZSH_PLUGINS[@]}})"
}
