# dreamzsh/core/config.zsh

if [[ -n "${__DREAMZSH_CONFIG_LOADED:-}" ]]; then
  return 0
fi
__DREAMZSH_CONFIG_LOADED=1

source "${DREAMZSH_DIR}/core/utils.zsh" || return 1

typeset -g DREAMZSH_THEME=""
typeset -ga DREAMZSH_PLUGINS=()
typeset -g DREAMZSH_PROFILE=""
typeset -g DREAMZSH_VERSION="2"

dz::config::set_defaults() {
  : "${DREAMZSH_THEME:=minimal}"
  : "${DREAMZSH_PROFILE:=default}"

  if (( ${#DREAMZSH_PLUGINS[@]} == 0 )); then
    DREAMZSH_PLUGINS=(git history navigation)
  fi
}

dz::config::load() {
  if [[ -f "$DREAMZSH_CONFIG_FILE" ]]; then
    source "$DREAMZSH_CONFIG_FILE" || {
      dz::error "Failed to load config: $DREAMZSH_CONFIG_FILE"
      return 1
    }
  fi

  dz::config::set_defaults
}

dz::config::save() {
  dz::ensure_dir "$DREAMZSH_DIR" || return 1

  cat >| "$DREAMZSH_CONFIG_FILE" <<EOF
# DreamZSH configuration
# Generated by DreamZSH CLI

DREAMZSH_VERSION="2"
DREAMZSH_THEME="${DREAMZSH_THEME}"
DREAMZSH_PROFILE="${DREAMZSH_PROFILE}"
DREAMZSH_PLUGINS=(${(j: :)${(q)DREAMZSH_PLUGINS[@]}})
EOF
}

dz::config::print() {
  print -r -- "DREAMZSH_VERSION=\"$DREAMZSH_VERSION\""
  print -r -- "DREAMZSH_THEME=\"$DREAMZSH_THEME\""
  print -r -- "DREAMZSH_PROFILE=\"$DREAMZSH_PROFILE\""
  print -r -- "DREAMZSH_PLUGINS=(${(j: :)${(q)DREAMZSH_PLUGINS[@]}})"
}
