# Tokyo Night palette for DreamZSH.

DZ_PALETTE_USER_BG="#bb9af7"
DZ_PALETTE_PATH_BG="#7aa2f7"
DZ_PALETTE_PATH_FG="#1a1b26"
DZ_PALETTE_GIT_BG="#9ece6a"
DZ_PALETTE_GIT_FG="#1a1b26"
DZ_PALETTE_ACCENT="#7dcfff"
DZ_PALETTE_SUCCESS="#9ece6a"
DZ_PALETTE_ERROR="#f7768e"
DZ_PALETTE_MUTED="#565f89"
DZ_PALETTE_DARK="#1a1b26"

source "${DREAMZSH_THEMES_DIR}/_palette.zsh"
